version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflowuser
      POSTGRES_PASSWORD: taskflowpassword
    ports:
      - "5432:5432"
    volumes:
      - taskflow-postgres-data:/var/lib/postgresql/data

volumes:
  taskflow-postgres-data: